# Generated by Django 6.1 on 2026-10-05 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Foto / Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Identificador (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=260, unique=True, verbose_name='Identificador (slug)')),
                ('summary', models.TextField(help_text='Breve descripción para listados y tarjetas.', verbose_name='Resumen / Copete')),
                ('content', models.TextField(help_text='Contenido completo.', verbose_name='Cuerpo de la noticia')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Imagen destacada')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('is_published', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.author', verbose_name='Autor')),
                ('categories', models.ManyToManyField(related_name='articles', to='news.category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Noticia / Artículo',
                'verbose_name_plural': 'Noticias / Artículos',
                'ordering': ['-published_date'],
            },
        ),
    ]
